import Head from "next/head";
import { useState } from "react";


export default function Home() {
  const [employees, setEmployees] = useState([]);

  async function fetchEmployees() {
    const res = await fetch("/api/employees");

    if (res.ok) {
      const resJson = await res.json();
      setEmployees(resJson);
    }
  }

  return (
    <>
      <Head>
        <title>EIP employees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ padding: "50px" }}>
        <h1>EiP Employees</h1>
        <button onClick={fetchEmployees}>fetch employees</button>

        {employees.length > 0 &&
          employees.map((employee) => (
            <div key={employee.name}>
              <h2>{employee.name}</h2>
              <h3>{employee.team}</h3>
              <p>{employee.startDate}</p>
            </div>
          ))}
      </main>
    </>
  );
}
